### ISSUE TITLE
Please reopen #16: Adjust Baro Altitude to QNH

### ISSUE THREAD

**Issue by DocTopi** [knicholson32/stratux_ahrs#24]
Sorry, i´m not familiar with GitHub ...
Is it possible for me to reopen a closed issue?
Below issue #16 i wrote a request for an enhancement, but i´m not sure if you are notified because this issue is closed.
Thank you for your answer.

**Comment by knicholson32** [comment]
Re-opened #16, closing this issue. Thanks!
